name: Run Cypress Tests
on: push
jobs:
  run_cypress:
     name: Run Cypress
     runs-on: ubuntu-18.04
     timeout-minutes: 20
     steps:
       - name: Checkout
         uses: actions/checkout@v1

       - name: Cypress Run
         uses: cypress-io/github-actions@v2
         with:
           start: yarn dev
           config-file: cypress.json
           wait-on: "http://localhost:3000"
           wait-on-timeout: 300
           browser: chrome
           headless: true
